### ISSUE TITLE
Errors creating replicated tables

### ISSUE THREAD

**Issue by migue** [kshvakov/clickhouse#108]
Hello all,

First of all, thanks for the driver, it's being really useful :).

We're running into a problem that I would like to describe here: we make use of the ClickHouse abilities to replicate tables and we're getting errors while we try to create the table in all the nodes of the cluster

Cluster
------
Our current setup is a ClickHouse cluster with 3 shards; every shard contains two replicas
```
    	<us-west-2>
        	<shard>
            	<internal_replication>true</internal_replication>
            	<replica>
                	<host>clickhouse-1-us-west-2</host>
                	<port>9000</port>
           		</replica>
            	<replica>
                	<host>clickhouse-2-us-west-2</host>
                	<port>9000</port>
           		</replica>
        	</shard>
        	<shard>
            	<internal_replication>true</internal_replication>
            	<replica>
                	<host>clickhouse-3-us-west-2</host>
                	<port>9000</port>
           		</replica>
            	<replica>
                	<host>clickhouse-4-us-west-2</host>
                	<port>9000</port>
           		</replica>
        	</shard>
        	<shard>
            	<internal_replication>true</internal_replication>
            	<replica>
                	<host>clickhouse-5-us-west-2</host>
                	<port>9000</port>
           		</replica>
            	<replica>
                	<host>clickhouse-6-us-west-2</host>
                	<port>9000</port>
           		</replica>
        	</shard>
    	</us-west-2>
```

Queries
-------

We're trying to create a replicated table in all the six previous nodes (we cannot make use of the `ON CLUSTER` directive)

```
CREATE TABLE IF NOT EXISTS local_calls (
    trace_id String,
    call_id String,
    date Date MATERIALIZED toDate(t/1000),
    t UInt64,
    a UInt64,
    b String,
    c String
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/local_calls', '{replica}') PARTITION BY toRelativeDayNum(date) ORDER BY t SETTINGS index_granularity=8192;
```
I am removing most of the columns for the sake of simplicity

Problem
-------

When we try to run the query on every node, we get the following error:

```
(details: code: 122, message: Table structure in ZooKeeper is too different from local table structure)’
```
We get in every replica node: so if we run the queries in the following order: clickhouse-1 to clickhouse-6, we get the errors in nodes 2, 4 and 6

Analysis
-----

I am not 100% sure, but, what I think it's happening is that the columns are being sent in a different order when the query is submitted to the second replica.

So, the first create statement is sent to clickhouse-1, the table is created and all the metadata is stored in Zookeeper, then, when the same query is sent to clickhouse-2, the columns are sent in a different order: the node will check the actual query statement against the metadata stored in Zookeeper (because it's a replicated table) an it will fail with an error like the one already described.

Does it make sense?

Please, let me know if I can help some how (in case this is a real issue :) )

**Comment by kshvakov** [comment]
Hi, I think it's a ClickHouse problem/bug. Try to create the table without a slash in default value (`date Date MATERIALIZED toDate(t/1000)` )

**Comment by migue** [comment]
I will give it a try.

Just would like to add that creating the tables using regular HTTP requests works fine

**Comment by kshvakov** [comment]
It's very strange. I'll troubleshoot it

**Comment by migue** [comment]
I've followed the same process using and HTTP Client and the command line (which uses the TCP protocol, doesn't it) and both works for me.

The only way I am able to reproduce the issue is using the driver

**Comment by kshvakov** [comment]
OK, I'll be back on Monday and fix it.

**Comment by marcelbirkner** [comment]
Hi @kshvakov,

do you have any news on this ticket? Where you able to reproduce the problem we encountered?
If there is anything we can do to help out, let us know.

Thanks,
Marcel

**Comment by sigil66** [comment]
I had hoped this was an instance of a map being ranged over for columns being presented to the clickhouse server, however this does not seem to be the case :/

**Comment by sigil66** [comment]
You can ignore this.

The issue was that we were creating a table on one replica and then running all the migration alter statements. The next create would then fail because the initial create is the original table minus the alter deltas.
