### ISSUE TITLE
How to insert in batch

### ISSUE THREAD

**Issue by jc3wish** [kshvakov/clickhouse#109]
I need to write in batch . like:

insert into table (c1,c2,c3) values("1","2","3"),("11","22","33");

What should I do?

**Comment by derekperkins** [comment]
Use a prepared statement
https://github.com/kshvakov/clickhouse/blob/master/examples/multiple.go#L42-L60

**Comment by kamly** [comment]
@derekperkins 

the example 

```
stmt, err := tx.Prepare("INSERT INTO example_%d (country_code, os_id, ) VALUES (?, ?)")
for i := 0; i < 100; i++ {
	if _, err := stmt.Exec(
	     // ...
	); err != nil {
		log.Fatal(err)
	}
}
```
real exec sql is  `INSERT INTO example_%d (country_code, os_id, ) VALUES (xxx, xxx)` * 100

but i hope real exec sql is `INSERT INTO example_%d (country_code, os_id, ) VALUES (xxx, xxx),(xxx, xxx).....`

**Comment by charlie-wasp** [comment]
Wow, if that's true, it's really sabotaging the whole idea of batch inserting, isn't it?
