### ISSUE TITLE
Panic on WriteNull if v is uninitialized interface

### ISSUE THREAD

**Issue by ivakhin** [kshvakov/clickhouse#133]
https://golang.org/pkg/reflect/#Value.IsNil

> if v was created by calling ValueOf with an uninitialized interface variable i, i==nil will be true but v.IsNil will panic as v will be the zero Value.

https://github.com/kshvakov/clickhouse/blob/60cb4d4d7fa7f5609736d1bed4c328656e3bba0e/lib/column/nullable.go#L54

**Comment by kshvakov** [comment]
Hi, the master branch is broken, I'll fix it today.

**Comment by ivakhin** [comment]
Thx!

**Comment by ivakhin** [comment]
`if value := reflect.ValueOf(v); v == nil || (value.Kind() == reflect.Ptr && value.IsNil()) {`
if you want to check whether the value of the pointer is equal to nil, you should use [Elem()](https://golang.org/pkg/reflect/#Value.Elem)
`if value := reflect.ValueOf(v); v == nil || (value.Kind() == reflect.Ptr && value.Elem().IsNil()) {`
https://play.golang.org/p/sO-XnoM2V9l

**Comment by kshvakov** [comment]
It's needed only for the uninitialized values like 

```go 
var i *int
```
Using  `Elem`  can break execution(https://play.golang.org/p/YICCLvVNKjn)
