### ISSUE TITLE
connet read error: i/o timeout

### ISSUE THREAD

**Issue by beckyxu** [kshvakov/clickhouse#147]
clickhouse][connect=1][connect] read error: read tcp xxx:57577->xxx:8123: i/o timeout
func main() {
	connect, err := sqlx.Open("clickhouse", "http://xxx:8123?username=xxx&password=xxx&database=xxx&read_timeout=20&write_timeout=30&debug=true")
	if err != nil {
		log.Fatal(err)
	}
	var items []struct {
		Day time.Time    `db:"day"`
		SwitchSn        string     `db:"switchSn"`
		Ip   string     `db:"ip"`
		Index  string  `db:"index"`
		Value  string `db:"value"`
		Type   string     `db:"type"`
		CollectionTime  time.Time   `db:"collectionTime"`
	}

	connect.SetConnMaxLifetime(time.Minute)
	if err := connect.Select(&items, "SELECT day,switchSn,ip,index,value,type,collectionTime FROM devops.switch_data_collect WHERE day=toDate( '2018-12-8') LIMIT 1"); err != nil {
		log.Fatal(err)
	}

	for _, item := range items {
		log.Printf("country: %v, os: %v, browser: %v, categories: %v, action_time: %v  %v", item.Day, item.SwitchSn, item.Ip, item.Index, item.Value,item.Type)
	}
}

username and password is right,but I can't connect. use other such as:github.com/mailru/go-clickhouse  I can connet.

**Comment by kshvakov** [comment]
Incorrect port, use 9000.

**Comment by HelloKevinTian** [comment]
for clickhouse:
8123 -> http
9000 -> tcp
