### ISSUE TITLE
LIKE query not working

### ISSUE THREAD

**Issue by berupp** [kshvakov/clickhouse#173]
Hi

I tried to write some LIKE queries and found a bug. 
I added tests to reproduce: https://github.com/kshvakov/clickhouse/pull/174 

When providing the wildcard operators as part of the parameter:
```
x.Query("SELECT * from X WHERE Y LIKE ?", "%param%")
```
the query fails with `sql: expected 0 arguments, got 1`:

This is because `%` is the keyword for identifying LIKE operators. Defining the wildcards in the query string, will detect the argument:
```
x.Query("SELECT * from X WHERE Y LIKE %?%", "param")
```
but due to the next argument being quoted, the SQL becomes invalid:
```
SELECT * from X WHERE Y LIKE %'param'%
```
as the wildcards are outside the quoted parameter.

https://github.com/kshvakov/clickhouse/pull/174 utilizes the existing matcher to define `like` as a keyword for LIKE queries. The user supplies wildcards as part of the provided parameter.

**Comment by kshvakov** [comment]
Hey. Why did you close the PR?

**Comment by berupp** [comment]
Sorry I cleaned it up :) I opened a new PR with a few more tests

**Comment by kshvakov** [comment]
Good job! Thank you:)
