### ISSUE TITLE
Allow to set parameters when connecting to Clickhouse server

### ISSUE THREAD

**Issue by altush1983** [kshvakov/clickhouse#176]
Can you allow to set parameter max_partitions_per_insert_block on connect to DB like in clickhouse-client (command clickhouse-client -h 127.0.0.1 --max_partitions_per_insert_block=4999 works ok)?
It looks like very useful because for different connection this parameter should be different for better error control.
For example: sql.Open("clickhouse", 'tcp://localhost:9000/?username=test&password=123&database=test&timeout=1s&max_partitions_per_insert_block=4999')

**Comment by forward32** [comment]
@altush1983 It's implemented now!
Please check it out and let me know if you find any bugs, thanks.
