### ISSUE TITLE
Support for JsonEachRow Insert

### ISSUE THREAD

**Issue by luongdieu86** [kshvakov/clickhouse#182]
Hi,
Can I use JsonEachRow insert statement to insert Json data to Clickhouse ?

**Comment by blinkov** [comment]
@luongdie86 yes

**Comment by luongdieu86** [comment]
I've try to use 
if _, err := connect.Exec("DROP TABLE example"); err != nil {
		log.Fatal(err)
}
but it's got error :
2019/06/25 02:40:07 insert statement supported only in the batch mode (use begin/commit)

Should I use Prepare statement, I using for loop to insert record by record.
I want to use insert JsonEachRow to insert multiple record a time:
Ex:
insert into  test FORMAT JSONEachRow {"data":1}, {"data":2}, {"data":3}

**Comment by finnan444** [comment]
@luongdieu86 
This library allows to insert data only within so called transaction - not database transaction since lickhouse doesnt support it
see #138

**Comment by luongdieu86** [comment]
@finnan444 
It's mean that, to insert data using this Lib, we have to use transaction and prepare statement.
Example:
>var (
		tx, _   = connect.Begin()
		stmt, _ = tx.Prepare(`insert into example FORMAT JSONEachRow {"data":? } `)
	)
	defer stmt.Close()

	for i := 0; i < 100; i++ {
		if _, err := stmt.Exec(
			"test",			
		); err != nil {
			log.Fatal(err)
		}
	}

	if err := tx.Commit(); err != nil {
		log.Fatal(err)
	}

But output log show that:
>[clickhouse][connect=1][begin] tx=false, data=false
[clickhouse][connect=1][prepare] insert into example FORMAT JSONEachRow {"data":?}
[clickhouse][connect=1][send query] insert into example FORMAT JSONEachRow {"data":?}  VALUES
[clickhouse][connect=1][read meta] <- data: packet=1, columns=4, rows=0
2019/06/28 00:52:51 sql: expected 4 arguments, got 1
exit status 1


Beside, base on source code
clickhouse.go , line 84
>if err := ch.sendQuery(splitInsertRe.Split(query, -1)[0] + " VALUES "); err != nil {

Library will append "VALUES" key to SQL command. 
I think that, **it's can not** support for Insert by JSONEachRow:
https://clickhouse.yandex/docs/en/interfaces/formats/#jsoneachrow

>INSERT INTO UserActivity FORMAT JSONEachRow {"PageViews":5, "UserID":"4324182021466249494", "Duration":146,"Sign":-1} {"UserID":"4324182021466249494","PageViews":6,"Duration":185,"Sign":1}

**Comment by kshvakov** [comment]
`FORMAT` is not supported by the driver. The driver sends binary blocks (columns) to the ClickHouse server   and doesn't parse FORMAT section

**Comment by luongdieu86** [comment]
@kshvakov Understood, thank you.

**Comment by bakuljajan** [comment]
> `FORMAT` is not supported by the driver. The driver sends binary blocks (columns) to the ClickHouse server and doesn't parse FORMAT section

@kshvakov does this still true in v2? Do you have any example of how to insert `JSONEachRow` without using `FORMAT`?
