### ISSUE TITLE
uuid.Value panics

### ISSUE THREAD

**Issue by finnan444** [kshvakov/clickhouse#183]
Such code: 
``` clickhouse.UUID("").Value() ```
leads to panic (```panic: runtime error: index out of range```)
I think it should check ```len(str)``` and return nil, InvalidUUIDFormatError before line 54, which panics:
```golang
 if str[8] != '-' || str[13] != '-' || str[18] != '-' || str[23] != '-' {
		return nil, InvalidUUIDFormatError
	}
```

+ why type UUID will be deprecated?

**Comment by kshvakov** [comment]
> why type UUID will be deprecated? 
Hi, because UUID is now supported by ClickHouse

**Comment by finnan444** [comment]
> > why type UUID will be deprecated?
> 
> Hi, because UUID is now supported by ClickHouse

Yeah, i've read your comment in code. If it is now supported, then of course it should be supported by driver, see issue #184

**Comment by kshvakov** [comment]
#184 is bug, Nullable types is partially supported by the driver
