### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by valeriy-efimov** [kshvakov/clickhouse#185]
how to send a password? If it is difficult
"Dsd0@*E)0#jsdpAS)DJD*!)d0@*d"
`connect, err := sql.Open("clickhouse", "tcp://127.0.0.1:9000?username=default&password=Dsd0@*E)0#jsdpAS)DJD*!)d0@*d&database=database&read_timeout=10&write_timeout=20")`
they correct but ger error "[193] Wrong password for user default "

**Comment by Slach** [comment]
you shouldn't use "#" in password, sql.Open try parse connection string

**Comment by valeriy-efimov** [comment]
> you shouldn't use "#" in password, sql.Open try parse connection string

пароль генерировал не я. Соответственно изменить его не могу =(
