### ISSUE TITLE
Compress buffer size is smaller than documented in the comment

### ISSUE THREAD

**Issue by ryanworl** [kshvakov/clickhouse#215]
https://github.com/kshvakov/clickhouse/blob/1fd26158e61b4d96fa69eee9aa7518ef65854cba/lib/binary/compress_settings.go#L19-L20

This should be `1 << 20` and not the current value to match the comment.

**Comment by richardartoul** [comment]
#217 Will resolve this

**Comment by richardartoul** [comment]
This can be closed now
