### ISSUE TITLE
statement expects 0 inputs; got 1 while using sql.NamedArgs

### ISSUE THREAD

**Issue by marcelcorso** [kshvakov/clickhouse#22]
On go 1.8 the sql package started to support [NamedArg](https://golang.org/pkg/database/sql/#NamedArg)s. 

I just tried to add 

```go
        rows, err = connect.Query("SELECT * FROM example WHERE os_id = @os_id", sql.Named("os_id", 10))
        if err != nil {
                log.Fatal(err)
        }
```

to the [simple.go](https://github.com/kshvakov/clickhouse/blob/master/examples/simple.go) example and got the error 

```
[clickhouse]host(s)=127.0.0.1:9000, database=default, username=default
[clickhouse][hello] -> Golang SQLDriver 1.1.54126
[clickhouse][hello] <- ClickHouse 1.1.54180 (Etc/UTC)
[clickhouse][prepare] SELECT * FROM example WHERE os_id = @os_id
[clickhouse][stmt] close
2017/03/22 15:27:22 sql: statement expects 0 inputs; got 1
```

```
$> go version
go version go1.8 linux/amd64
```

**Comment by kshvakov** [comment]
Hi, full features Go 1.8 is't supported of current driver version. I'll be add NamedArgs support in the next couple of days

thank you

**Comment by marcelcorso** [comment]
thanks @kshvakov. I tested the changes on 2 places and it worked. Code is 👍 too.

**Comment by marcelcorso** [comment]
The code

```
rows, err = connect.Query("SELECT * FROM example WHERE os_id = @os_id AND browser_id = @os_id", sql.Named("os_id", 10))
```

fails with 

```
2017/03/24 09:58:33 sql: statement expects 2 inputs; got 1
```

I didn't find any specific recommendation on how this should work and there are no tests for this specific case on the sql package
https://github.com/golang/go/blob/master/src/database/sql/sql_test.go#L513

but it feels it should work.

**Comment by marcelcorso** [comment]
https://github.com/golang/go/issues/12381

**Comment by marcelcorso** [comment]
Thanks @kshvakov  that was fast. 

But this

```golang
rows, err = connect.Query("SELECT * FROM example WHERE os_id in (@os_id,@browser_id) browser_id = @browser_id", sql.Named("os_id", 10), sql.Named("browser_id", 77))
```

(note the lack of space between ```@os_id,@browser_id```

breaks with the message

```sql: statement expects 1 inputs; got 2```


And with the space between the parameters 

```golang
rows, err = connect.Query("SELECT * FROM example WHERE os_id IN (@os_id, @browser_id) AND browser_id = @browser_id", sql.Named("os_id", 10), sql.Named("browser_id", 77))
```


I get a different error:

```
code: 62, message: Syntax error: failed at position 39: @os_id, @browser_id) AND browser_id = 77, expected )
```

**Comment by kshvakov** [comment]
Yes, I know. I'll fix this problem  in the next couple of days

**Comment by marcelcorso** [comment]
I just tested the new code with a bunch of use cases and it looks good. 👍
