### ISSUE TITLE
Round Robin load-balancing not working

### ISSUE THREAD

**Issue by marcelcorso** [kshvakov/clickhouse#24]
I just tried the round-robin load balancing and found out that it is not scheduling connections according to the round robin algorithm 

With this example DSN:

`tcp://clickhouse-000:9000?username=&debug=true&alt_hosts=clickhouse-001:9000,clickhouse-002:9000`

1) Concurrent requests should be balanced

I just tried sending many concurrent requests and all requests get sent to clickhouse-000. 

2) Unhealthy connections should not be retried after an error 

 - send a query, it hits clickhouse-000
 - bring down clickhouse-000
 - send a query, it hits clickhouse-000 and fails 
 - send a query, it hits clickhouse-000, fails again
...

**Comment by kshvakov** [comment]
I resolved a problem with reconnecting and add output about connection host to debug log.  For simulation parallel execution you will be executed this code 
```go
package main

import (
	"database/sql"
	"log"

	_ "github.com/kshvakov/clickhouse"
)

func main() {
	connect, err := sql.Open("clickhouse", "tcp://127.0.0.1:9000?username=&compress=true&debug=true&alt_hosts=127.0.0.2:9000")
	checkErr(err)
// open concurrent transactions 
	connect.Begin()
	connect.Begin()
	connect.Begin()
	connect.Begin()

}
func checkErr(err error) {
	if err != nil {
		log.Fatal(err)
	}
}
```
output
```
kshvakov@kshvakov:~$ go run example.go | grep conn
[clickhouse]connect[1] to: 127.0.0.1:9000
[clickhouse]connect[2] to: 127.0.0.2:9000
[clickhouse]connect[3] to: 127.0.0.1:9000
[clickhouse]connect[4] to: 127.0.0.2:9000
```

**Comment by marcelcorso** [comment]
Thanks, you are right and I saw different connections being used on the parallel requests case. 



But I'm still having the error where it tries for ever to send queries to a connection that failed

```
2017/03/25 03:48:50 code: 279, message: All connection tries failed. Log:

Code: 210, e.displayText() = DB::NetException: Connection refused: (127.0.0.1:9000), e.what() = DB::NetException
Code: 210, e.displayText() = DB::NetException: Connection refused: (127.0.0.1:9000), e.what() = DB::NetException
Code: 210, e.displayText() = DB::NetException: Connection refused: (127.0.0.1:9000), e.what() = DB::NetException
```

Maybe the error is not of the type net.OpError and this type assertion fails?

```go
if _, ok := err.(*net.OpError); ok {
      return n, driver.ErrBadConn
}
```

**Comment by marcelcorso** [comment]
Cool. We tested over here and it's working fine. Thanks!! 
👍
