### ISSUE TITLE
How to insert UUID

### ISSUE THREAD

**Issue by daskol** [kshvakov/clickhouse#26]
How to insert UUID in standard representation `00000000-0000-0000-0000-000000000000` into column of type `FixedString(16)`?

I faced to curios behavior that `UUIDStringToNum()` does not works as expected in query
```sql
    INSERT INTO table (
        date, uuid
    ) VALUES (
        ?, UUIDStringToNum(?)
    );
```
Golang is as following
```go
    _, err := stmt.Exec(time.Now(), 5d272320-e688-410e-bfba-03d43bb3099c)
```
Error message is `column uuid (FixedString(16)): too large value`.

**Comment by kshvakov** [comment]
User function could not work in native protocol

This driver send only data to server without transformation

**Comment by daskol** [comment]
@kshvakov Sure, but bash command like
```bash
clickhouse-client <<< "INSERT INTO table (date, uuid) VALUES ('2017-01-01', 5d272320-e688-410e-bfba-03d43bb3099c);"
```
works properly.

**Comment by kshvakov** [comment]
I know, clickhouse-client transform data on its side
how it works

client send a query to the server
```
INSERT INTO table (
        date, uuid
    ) VALUES
```
 server say: ok, give me the data: 2 columns with types Date(number of days since 1970) and FixedString(16) (16 bytes not utf:))

**Comment by kshvakov** [comment]
UUID is now supported 

You can write it like this: 

```go 
_, err := stmt.Exec(time.Now(), clickhouse.UUID("5d272320-e688-410e-bfba-03d43bb3099c"))
```
