### ISSUE TITLE
Support multiple insert

### ISSUE THREAD

**Issue by Upliner** [kshvakov/clickhouse#28]
Statements like INSERT INTO table(a,b,c) VALUES (?,?,?), (?,?,?)... is currently not supported, I can try to fix it...

**Comment by kshvakov** [comment]
Why is it necessary?

**Comment by Upliner** [comment]
One insert query may be faster for large bulk inserts.

**Comment by kshvakov** [comment]
No, It does not work the way you think. You'll can use batch mode: begin->prepare->in loop execute->commit
