### ISSUE TITLE
toColumn type fails on high-batch load

### ISSUE THREAD

**Issue by kenota** [kshvakov/clickhouse#34]
Observed behaviour: on high batch load toColumn types randomly fails
Expected behaviour: no failure while database is up

Environment:

go version go1.8.1 darwin/amd64
Golang SQLDriver 1.1.54213
ClickHouse 1.1.54140 (Universal)
Docker version 17.03.1-ce, build c6d412e
CPU: 2.3 GHz Intel Core i7
RAM: 16GB

Clickhouse is running inside docker on Mac on the same machine.
Docker has 8Gb of RAM allocated. 

Steps to reproduce

1. Copy this gist and save it as `main.go` https://gist.github.com/kenota/513e304805479a5f40108618bbe45678
2. Start clickhouse, for example using docker: `docker run -p 8123:8123 -p 9000:9000 -d --name click2 --ulimit nofile=262144:262144 yandex/clickhouse-server`
3. Run test code and wait (should be under 1 minute)  for panic to happen: `go run main.go`

Using code provided I am able to receive reliable panics under 10 minutes running on my machine:

Here are sample panics:
```
go-click-test kenota$ go run main.go
2017/05/24 21:22:59 Test is running...
panic: func toColumnType: unhandled type nt16

goroutine 7 [running]:
main.getTemplate(0x1225d20, 0xc4200b0000, 0x0, 0x0, 0x0)
	.../main.go:59 +0xa5
main.worker(0x0)
	.../main.go:79 +0x1d2
created by main.main
	.../main.go:108 +0x56
exit status 2
go-click-test kenota$ go run main.go
2017/05/24 21:23:51 Test is running...
panic: func toColumnType: unhandled type nt16

goroutine 7 [running]:
main.getTemplate(0x1225d20, 0xc4200b0000, 0x0, 0x0, 0x0)
	.../main.go:59 +0xa5
main.worker(0x0)
	.../main.go:79 +0x1d2
created by main.main
	.../main.go:108 +0x56
exit status 2
```
Some times in takes longer, sometimes it happens faster. 

I was struggling to reproduce it on sample code at all before I made a change. In sample code in worker function there is perIteration variable. Initially I set it to 1000 and was not able to trigger the issue. Then I realised that in my real app buffer is not always filled to 1000 ( the limit of the buffer) and there are quite a lot of batches with only ~hundreds events in them. I have changed the code to randomise number of iterations and include lower range and viola -- the error starts happening.

While I was creating this ticket I decided to try and  simplify code even more. You will see that there is `requests` array. In the beginning there were 3 go routines doing inserts into 3 different tables. But I decided to switch it to one and bug still happening.

This drives me to conclusion that it is somehow related to frequency of Prepare()/Commit() and number of calls to Execs. Perhaps this is even bug in clickhouse? It seems that for batch inserts it is creating temporary table and then merging it in.

**Comment by kshvakov** [comment]
Try to use std Go database/driver interface (use "direct" only for very high performance), example: 

```go
package main

import (
	"database/sql"
	"fmt"
	"log"
	"time"

	"github.com/kshvakov/clickhouse"
)

func main() {
	connect, err := sql.Open("clickhouse", "tcp://127.0.0.1:9000?username=&compress=true&debug=true")
	checkErr(err)
	if err := connect.Ping(); err != nil {
		if exception, ok := err.(*clickhouse.Exception); ok {
			fmt.Printf("[%d] %s \n%s\n", exception.Code, exception.Message, exception.StackTrace)
		} else {
			fmt.Println(err)
		}
		return
	}
	for i := 0; i < 10; i++ {
		_, err = connect.Exec(fmt.Sprintf(`
		CREATE TABLE IF NOT EXISTS multiple_%d (
			country_code FixedString(2),
			os_id        UInt8,
			browser_id   UInt8,
			categories   Array(Int16),
			action_day   Date,
			action_time  DateTime
		)  engine=MergeTree(action_day, action_day, 8192)
	`, i))

		checkErr(err)
	}
	for i := 0; i < 10; i++ {
		go func(i int) {
			for {
				tx, err := connect.Begin()
				checkErr(err)
				stmt, err := tx.Prepare(fmt.Sprintf("INSERT INTO multiple_%d (country_code, os_id, browser_id, categories, action_day, action_time) VALUES (?, ?, ?, ?, ?, ?)", i))
				checkErr(err)

				for i := 0; i < 10000; i++ {
					if _, err := stmt.Exec(
						"CY",
						10+i,
						100+i,
						clickhouse.Array([]int16{1, 2, 3}),
						time.Now(),
						time.Now(),
					); err != nil {
						log.Fatal(err)
					}
				}
				checkErr(tx.Commit())
				time.Sleep(time.Second)
			}
		}(i)
	}
	<-make(chan bool)
}

func checkErr(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

```

and upgrade your ClickHouse server, because of driver version (1.1.54213) higher server version (1.1.54140).
PS: It's also not recommended small batch inserts (less than 1000 rows) to ClickHouse and no more than 1 request per second, and no parallel request to the table because it's very slow and  hard for ClickHouse server 

PS2: I can't reproduce on the server, I'll try to reproduce on my Mac laptop

**Comment by kenota** [comment]
I know about recommendation of having larger batch inserts and I will definitely rewrite app to ensure that there at least 1000 rows in batch, on insert.

But I think we might encounter issue which needs to be fixed anyway. I run my test while running tcpdump. Once it crashed I see that the last reply from server is broken down into two packets where first one has UI  and second has nt16 for describing cid column. The crash message complains about nt16 not being correct type. 

Can it be perhaps that if reply is split between two packets then client can not read it correctly?

See attached screenshots.

![first part](https://cloud.githubusercontent.com/assets/1538669/26454507/36c7a852-415f-11e7-89d3-59c4d001f9be.png)
![second part](https://cloud.githubusercontent.com/assets/1538669/26454506/36b700a6-415f-11e7-8b68-0cbcfa1cb174.png)

**Comment by kshvakov** [comment]
I try to reproduce

**Comment by kshvakov** [comment]
Pls, check last version `go get -u github.com/kshvakov/clickhouse`

**Comment by kenota** [comment]
Tried, same problem.  Double checked file $GOPATH/github.com/kshvakov/clickhouse/connect.go to make sure its updated. Still same exception. 

Did you try to reproduce while running clickhouse on the same machine? Just wondering if the fact of using lo0 somehow affects packet size/fragmentation.

**Comment by kshvakov** [comment]
I can reproduce this bug on MacOS

**Comment by kshvakov** [comment]
I fixed this bug, try again, please

**Comment by kenota** [comment]
I tried it both on test code and on real code with no crash so far. Left it it running for quite a while, so I think the bug is now fixed. 

Thank you for fixing it so quickly!
