### ISSUE TITLE
Add context support

### ISSUE THREAD

**Issue by bgaifullin** [kshvakov/clickhouse#37]
Please correct me if I am wrong, but now the driver implements interfaces to support context, but actually it does not provide full support for context.Context.

**Comment by kshvakov** [comment]
Yes, the driver doesn't support full go 1.8 functionality at the moment. What the feature of context you want?

**Comment by bgaifullin** [comment]
I want cancelation by deadline or on demand.

**Comment by kshvakov** [comment]
I understood. I'll try to add the context functionality next week

**Comment by bgaifullin** [comment]
thanks.

**Comment by kshvakov** [comment]
done

**Comment by bgaifullin** [comment]
Thank you.
