### ISSUE TITLE
numInput returns wrong number if query contains '@'.

### ISSUE THREAD

**Issue by bgaifullin** [kshvakov/clickhouse#42]
I run the following statement:
```
INSERT INTO `dbr_people` (`id`,`name`,`email`) VALUES (258,'jonathan','jonathan@uservoice.com')
```

Expected result: it completes successful.
Actual Result: it fails with error: `sql: expected 1 arguments, got 0`

It occurs because numInput counts `@uservoice` as variable and returns 1 as number of input parameters. :(

**Comment by bgaifullin** [comment]
it is expected that `clickhouse` does not implement `Execer` and `Querier` interfaces ?

**Comment by bgaifullin** [comment]
If I fix this issue, I have the following:

```block: expected 3 arguments (columns: id, name, email), got 0```
I want to execute statement without arguments, because I use [dbr](https://github.com/mailru/dbr), which already interpolates all arguments.

**Comment by bgaifullin** [comment]
I used the following path for numInputs:
```
		if char, _, err := reader.ReadRune(); err == nil {
			switch char {
			case '\'', '"', '`':
				quote = !quote
			}
			if quote {
				continue
			}
			switch {
			case char == '?' && keyword:
```

**Comment by kshvakov** [comment]
Clickhouse doesn't support plain SQL insert requests over a native interface.  Query ```INSERT INTO `dbr_people` (`id`,`name`,`email`) VALUES (258,'jonathan','jonathan@uservoice.com')``` transforms to ```INSERT INTO `dbr_people` (`id`,`name`,`email`) VALUES``` and sent to the server then server waiting for the data block. 
I'll fix parser for the select requests  but is not very necessary

**Comment by bgaifullin** [comment]
Does it means, that I am not able to use click house with plain SQL?
I can execute query 'INSERT INTO `dbr_people` (`id`,`name`,`email`) VALUES (258,'jonathan','jonathan@uservoice.com')' via command-line client.

**Comment by kshvakov** [comment]
I know, clickhouse-client "prepare" query on its side, moreover, client execute all clickhouse functions and sending transformed data to the server
example    

```sql 
INSERT INTO t (date, uuid) VALUES ('2017-06-06', UUIDStringToNum('123e4567-e89b-12d3-a456-426655440000')) 
```
will be transform to query 
```sql 
INSERT INTO t (date, uuid) VALUES
```

end data block:  uint16 (date) + 16  []byte (uuid to FixedString)

**Comment by bgaifullin** [comment]
Do you have any ideas how plain SQL can be supported in driver?

**Comment by kshvakov** [comment]
Hmm, plain SQL for insertions is a bad idea not only for ClickHouse

**Comment by bgaifullin** [comment]
Why? if this SQL is checked for any kind of injections, what is reason to use placeholders?

**Comment by kshvakov** [comment]
Performance. Typical CH use case is a writing a lot of rows (hundreds of thousands of rows) in one request

**Comment by bgaifullin** [comment]
Ok, What is wrong if client uses plain SQL for this ?

**Comment by kshvakov** [comment]
It's very slow. A CH client should not parse SQL query and extract values from it. If you want to send plain SQL you can try to use CH Server HTTP-interface

**Comment by bgaifullin** [comment]
I need driver, because I want to add ClickHouse support into [dbr](https://github.com/mailru/dbr)

**Comment by kshvakov** [comment]
I think will be better to add support for prepared statements into  [dbr](https://github.com/mailru/dbr)

**Comment by bgaifullin** [comment]
It breaks one main features of DBR - query tracking, an user has ability to receive formatted query by implementing EventReceiver interface for any purpose. In our project it is uses to log queries.
if I add support for ClickHouse in dbr, I can switch from mysql to ClickHouse without changing the code.

**Comment by kshvakov** [comment]
Done. Plain SQL is now supported for selection queries. You can load your data using [go database/sql interface](https://github.com/kshvakov/clickhouse/blob/master/examples/simple.go) or use [direct interface](https://github.com/kshvakov/clickhouse/blob/master/examples/direct.go) for better performance

**Comment by bgaifullin** [comment]
thank you. I will close this issue, since it is resolved.
