### ISSUE TITLE
Support for Nullable() types

### ISSUE THREAD

**Issue by kenota** [kshvakov/clickhouse#48]
Is there plan to add support for Nullable() types?

**Comment by kshvakov** [comment]
Hi. Yes, I will add support for Nullable types

**Comment by kenota** [comment]
Do you accept PR's?

**Comment by kshvakov** [comment]
Yes, of course

**Comment by kshvakov** [comment]
now I'm on vacation if you have to add support for Nullable types you can see array implementation (it is very similar to implements new type)  or wait a couple of weeks )

**Comment by kshvakov** [comment]
New types Nullable and UUID are available in master

**Comment by kenota** [comment]
Thank you for adding this feature.
