### ISSUE TITLE
Подсчет ''?" в INSERT после Prepare()

### ISSUE THREAD

**Issue by Sfinks80** [kshvakov/clickhouse#52]
Уже после того, как клиент получил ответ на Prepare() от сервера и знает, сколько нужно аргументов на вставку одной строки, он все-равно продолжает проверять совпадение количества переданных в Exec() аргументов и знаков "?" в строке INSERT. Это сбивает с толку, когда при передаче совпадающего количества аргументов он то требует количество, равное количеству полей в строке,
`Can't execute statment (INSERT INTO events (uid, pid, event, geodata, created_at) FORMAT VALUES (?,?,?,?,?),(?,?,?,?,?),(?,?,?,?,?),(?,?,?,?,?)): block: expected 5 arguments (columns: uid, pid, event, geodata, created_at), got 20`
а при не совпадающем, количество, равное числу "?" в запросе
`Can't execute statment (INSERT INTO events (uid, pid, event, geodata, created_at) FORMAT VALUES (?,?,?,?,?),(?,?,?,?,?),(?,?,?,?,?),(?,?,?,?,?)): sql: expected 20 arguments, got 4`

**Comment by keakon** [comment]
@kshvakov I met the same bug (clickhouse-go v1.4.3):
block: expected 4 arguments (columns: date, time, srcip, destip), got 4000
