### ISSUE TITLE
Memory optimisations

### ISSUE THREAD

**Issue by AlekSi** [kshvakov/clickhouse#53]
Our application that uses this driver spends a lot of CPU time on GC. Looking into pprof output, I see that most of the allocated objects are created in `insert()` code branch. It would be nice to reduce the number of allocated objects and to have some benchmarks for that in place.

**Comment by AlekSi** [comment]
One specific suggestion that may help: how about to use `sync.Pool` in `writeUvarint` and friends?

**Comment by kshvakov** [comment]
Hi, in the near future (i hope) driver will be using 1 encoder/decoder for connection (https://github.com/kshvakov/clickhouse/blob/refactoring/bootstrap.go#L98), and I'll try to reduce the number of allocated objects

**Comment by kshvakov** [comment]
Branch merged to master, you can try new version of lib

**Comment by AlekSi** [comment]
I see a 30% decrease in a number of allocations on our benchmarks, great job!

Do you plan to have Go benchmarks in this repo?

**Comment by kshvakov** [comment]
I didn't think about that )

**Comment by AlekSi** [comment]
I mean, not benchmarks of different Go versions, but benchmarks with `testing` package.

**Comment by kshvakov** [comment]
I have some benchmarks for lib ([lib/binary/binary_benchmark_test.go](https://github.com/kshvakov/clickhouse/blob/master/lib/binary/binary_benchmark_test.go) [lib/column/column_benchmark_test.go](https://github.com/kshvakov/clickhouse/blob/master/lib/column/column_benchmark_test.go)), and from time to time I write new tests
