### ISSUE TITLE
Docker Compose for local development and testing

### ISSUE THREAD

**Issue by AlekSi** [kshvakov/clickhouse#57]
I propose to add docker-compose.yml and use in both Travis CI and local development. Something like this we are doing in PromHouse:

* https://github.com/Percona-Lab/PromHouse/blob/master/.travis.yml
* https://github.com/Percona-Lab/PromHouse/blob/master/misc/docker-compose.yml
* https://github.com/Percona-Lab/PromHouse/blob/master/.github/CONTRIBUTING.md

**Comment by kshvakov** [comment]
It's a good idea, I'll add docker-compose file in the future or you can create a PR
