### ISSUE TITLE
Prepare and Nullable type.

### ISSUE THREAD

**Issue by arzonus** [kshvakov/clickhouse#65]
Hello!
When I try insert using tx.Prepare in query with Nullable columns, I have this error:
```
code: 50, message: Unknown type
```

If you try change prepare [in clickhouse_nullable test`](https://github.com/kshvakov/clickhouse/blob/master/clickhouse_test.go) in inserting of multiple rows, you will see this bug. 

Thanks.

**Comment by kshvakov** [comment]
Confirmed

**Comment by kshvakov** [comment]
Check it pls

**Comment by arzonus** [comment]
Yes, It's working! 
Thank you! :+1:
