### ISSUE TITLE
error when you go get 

### ISSUE THREAD

**Issue by nikulnik** [kshvakov/clickhouse#67]
..\..\kshvakov\clickhouse\clickhouse_read_block.go:12: ch.readTimeout undefined (type *clickhouse has no field or method readTimeout)
..\..\kshvakov\clickhouse\clickhouse_read_block.go:13: ch.writeTimeout undefined (type *clickhouse has no field or method writeTimeout)
..\..\kshvakov\clickhouse\clickhouse_read_block.go:15: ch.ServerInfo undefined (type *clickhouse has no field or method ServerInfo)
..\..\kshvakov\clickhouse\clickhouse_read_block.go:16: ch.decoder undefined (type *clickhouse has no field or method decoder)
..\..\kshvakov\clickhouse\clickhouse_read_block.go:20: ch.compress undefined (type *clickhouse has no field or method compress)
..\..\kshvakov\clickhouse\clickhouse_read_block.go:24: ch.ServerInfo undefined (type *clickhouse has no field or method ServerInfo)
..\..\kshvakov\clickhouse\clickhouse_read_block.go:24: ch.decoder undefined (type *clickhouse has no field or method decoder)
..\..\kshvakov\clickhouse\clickhouse_read_meta.go:12: ch.decoder undefined (type *clickhouse has no field or method decoder)
..\..\kshvakov\clickhouse\clickhouse_write_block.go:11: ch.Lock undefined (type *clickhouse has no field or method Lock)
..\..\kshvakov\clickhouse\clickhouse_write_block.go:12: ch.Unlock undefined (type *clickhouse has no field or method Unlock)
..\..\kshvakov\clickhouse\clickhouse_write_block.go:12: too many errors

**Comment by kshvakov** [comment]
Show your `go version`, `go env` and `ls -la "${GOPATH}/src/github.com/kshvakov/clickhouse"`

**Comment by nikulnik** [comment]
Sorry, everything is ok now I probably messed up some paths.

**Comment by nikulnik** [comment]
Sorry, everything is ok now I probably messed up some paths.
