### ISSUE TITLE
Big uint64 in Go 1.8 and Go 1.9

### ISSUE THREAD

**Issue by AlekSi** [kshvakov/clickhouse#69]
In Go 1.8, `ColumnConverter`/`ValueConverter` is used to convert big uint64 into a slice of bytes: https://github.com/kshvakov/clickhouse/blob/d09d76760d7867fcbea3655d027de907017b5411/value_converter.go#L47-L53 I'm not entirely sure how it should work, but it does not work for me for query arguments. Do you have a test for that?

In Go 1.9, `NamedValueChecker` is used, and it works. I assume there is a bug in Go documentation? Because `driver.Value` [by definition](https://golang.org/pkg/database/sql/driver/#Value) can't be uint64, and in `CheckNamedValue` you just pass it: https://github.com/kshvakov/clickhouse/blob/d09d76760d7867fcbea3655d027de907017b5411/clickhouse.go#L168-L169

The problem I see there that code compiles with both Go 1.8 and Go 1.9, and then fails in runtime if compiled with 1.8. I propose to either fix it for 1.8 or require 1.9+. The latter option will also allow you to remove some optional interfaces that are deprecated.

**Comment by kshvakov** [comment]
Hi, I have a test for big uint64 values and it works fine.  https://github.com/kshvakov/clickhouse/blob/master/issues_test.go#L44-L64 
Please, give an example for reproducing this bug 

Go 1.9 have a new algorithm for checking  values https://github.com/golang/go/blob/master/src/database/sql/convert.go#L164-L183

**Comment by AlekSi** [comment]
That may be fixed in 1.2.2 (I used 1.2), but #70 prevents me from updating.

**Comment by AlekSi** [comment]
May you please tag a new release?

**Comment by kshvakov** [comment]
Done
