### ISSUE TITLE
How to query for meta data like FORMAT JSON

### ISSUE THREAD

**Issue by elaijuh** [kshvakov/clickhouse#85]
should i use `FORMAT Native`?

**Comment by kshvakov** [comment]
It's impossible to get metadata over `database/sql`. But now I'm working on alternative interface with supporting ClickHouse features

**Comment by elaijuh** [comment]
which means i cannot get total rows when doing pagination by `LIMIT`?

**Comment by kshvakov** [comment]
No, only `SELECT COUNT(*) ...`

**Comment by elaijuh** [comment]
thanks
